name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm ci

    - name: build typescript
      run: npm run build

    - name: run tests and instrument coverage
      run: npm run coverage

    - name: check for unformatted sources
      run: |
        npm run format:check \
        || (echo "##[error] found unformatted files. please 'npm run format'" \
                 "and check in all changes" \
            && exit 1)

    - name: check for uncommitted changes
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build'" \
                 "and check in all changes" \
            && exit 1)

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        debug: true
      if: ${{ github.event_name == 'push' }}
